sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating image with docker file"
  - docker build -t chung9517/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true chung9517/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success!!!"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "Test react app"
  env: "TestReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-416350948385"
  bucket_path: :"Test React App"
  on:
    branch: master